-- KATE production schema: SQLite logical model translated to PostgreSQL.
-- Browser roles receive no table access. The Edge Function uses service_role server-side.

CREATE TABLE IF NOT EXISTS public.destinations (
  id text PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  country text NOT NULL CHECK (length(btrim(country)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.travel_intents (
  id text PRIMARY KEY,
  intent_type text NOT NULL CHECK (length(btrim(intent_type)) > 0),
  destination_id text REFERENCES public.destinations(id) ON DELETE SET NULL,
  stage text NOT NULL CHECK (length(btrim(stage)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.products (
  product_id text PRIMARY KEY,
  comparison_id text,
  search_partition text NOT NULL CHECK (search_partition IN ('road', 'fly', 'unresolved')),
  provider text,
  product_name text NOT NULL CHECK (length(btrim(product_name)) > 0),
  destination_text text,
  category text,
  from_price numeric(12,2) CHECK (from_price IS NULL OR from_price >= 0),
  currency text CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
  price_basis_confirmed boolean NOT NULL DEFAULT false,
  date_availability_confirmed boolean NOT NULL DEFAULT false,
  availability_state text NOT NULL DEFAULT 'unverified'
    CHECK (availability_state IN ('unverified', 'confirmed', 'unavailable', 'unknown')),
  affiliate_url text,
  affiliate_state text NOT NULL DEFAULT 'not_configured'
    CHECK (affiliate_state IN ('not_configured', 'pending', 'approved', 'rejected')),
  cancellation_note text,
  confidence_note text,
  snapshot_context jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(snapshot_context) = 'object'),
  source_last_checked timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (affiliate_state <> 'approved' OR affiliate_url IS NOT NULL),
  CHECK (availability_state <> 'confirmed' OR date_availability_confirmed)
);

CREATE TABLE IF NOT EXISTS public.opportunities (
  id text PRIMARY KEY,
  title text NOT NULL CHECK (length(btrim(title)) > 0),
  stage text NOT NULL CHECK (length(btrim(stage)) > 0),
  evidence_note text NOT NULL CHECK (length(btrim(evidence_note)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pages (
  path text PRIMARY KEY,
  page_name text NOT NULL CHECK (length(btrim(page_name)) > 0),
  intent text NOT NULL CHECK (length(btrim(intent)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.planner_sessions (
  id text PRIMARY KEY,
  origin text NOT NULL CHECK (length(btrim(origin)) > 0 AND length(origin) <= 80),
  focus text NOT NULL CHECK (focus IN ('maasai_mara', 'undecided')),
  days integer NOT NULL CHECK (days BETWEEN 1 AND 21),
  travelers integer NOT NULL CHECK (travelers BETWEEN 1 AND 20),
  budget_amount numeric(12,2) CHECK (budget_amount IS NULL OR budget_amount BETWEEN 0 AND 10000000),
  budget_currency text NOT NULL CHECK (budget_currency IN ('CHF', 'EUR', 'USD', 'GBP')),
  interests_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(interests_json) = 'array'),
  comfort text NOT NULL CHECK (comfort IN ('simple', 'balanced', 'more_comfort')),
  target_date date,
  date_flexibility text NOT NULL CHECK (date_flexibility IN ('fixed', 'flexible', 'not_sure')),
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz NOT NULL DEFAULT now(),
  output_summary text NOT NULL CHECK (length(btrim(output_summary)) > 0),
  CHECK (completed_at >= created_at)
);

CREATE TABLE IF NOT EXISTS public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL CHECK (length(btrim(event_type)) > 0),
  source text NOT NULL CHECK (length(btrim(source)) > 0),
  page text NOT NULL CHECK (length(btrim(page)) > 0),
  intent text,
  product_id text REFERENCES public.products(product_id) ON DELETE SET NULL,
  position text,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.affiliate_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL REFERENCES public.products(product_id) ON DELETE RESTRICT,
  destination_url text NOT NULL CHECK (destination_url ~ '^https://[^[:space:]]+$'),
  clicked_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversions (
  id text PRIMARY KEY,
  product_id text REFERENCES public.products(product_id) ON DELETE SET NULL,
  event_time timestamptz NOT NULL,
  source text NOT NULL CHECK (length(btrim(source)) > 0),
  verification_note text NOT NULL CHECK (length(btrim(verification_note)) > 0)
);

CREATE TABLE IF NOT EXISTS public.revenue (
  id text PRIMARY KEY,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  recorded_at timestamptz NOT NULL,
  evidence_note text NOT NULL CHECK (length(btrim(evidence_note)) > 0)
);

CREATE TABLE IF NOT EXISTS public.experiments (
  id text PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  status text NOT NULL CHECK (length(btrim(status)) > 0),
  hypothesis text NOT NULL CHECK (length(btrim(hypothesis)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.agent_runs (
  id text PRIMARY KEY,
  task text NOT NULL CHECK (length(btrim(task)) > 0),
  status text NOT NULL CHECK (length(btrim(status)) > 0),
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  outcome_note text,
  CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE IF NOT EXISTS public.business_memory (
  key text PRIMARY KEY CHECK (length(btrim(key)) > 0),
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.incidents (
  id text PRIMARY KEY,
  summary text NOT NULL CHECK (length(btrim(summary)) > 0),
  severity text NOT NULL CHECK (length(btrim(severity)) > 0),
  status text NOT NULL CHECK (length(btrim(status)) > 0),
  opened_at timestamptz NOT NULL,
  resolved_at timestamptz,
  CHECK (resolved_at IS NULL OR resolved_at >= opened_at)
);

CREATE INDEX IF NOT EXISTS travel_intents_stage_created_idx ON public.travel_intents(stage, created_at DESC);
CREATE INDEX IF NOT EXISTS products_comparison_partition_idx ON public.products(comparison_id, search_partition);
CREATE INDEX IF NOT EXISTS products_public_eligibility_idx ON public.products(availability_state, affiliate_state, product_id);
CREATE INDEX IF NOT EXISTS events_type_time_idx ON public.events(event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS events_page_type_time_idx ON public.events(page, event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS events_product_time_idx ON public.events(product_id, occurred_at DESC) WHERE product_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS affiliate_clicks_product_time_idx ON public.affiliate_clicks(product_id, clicked_at DESC);
CREATE INDEX IF NOT EXISTS conversions_product_time_idx ON public.conversions(product_id, event_time DESC);
CREATE INDEX IF NOT EXISTS revenue_recorded_at_idx ON public.revenue(recorded_at DESC);
CREATE INDEX IF NOT EXISTS planner_sessions_created_at_idx ON public.planner_sessions(created_at DESC);
CREATE INDEX IF NOT EXISTS agent_runs_status_started_idx ON public.agent_runs(status, started_at DESC);
CREATE INDEX IF NOT EXISTS incidents_status_severity_opened_idx ON public.incidents(status, severity, opened_at DESC);

-- Atomic planner completion. Callable only by the trusted server-side service role.
CREATE OR REPLACE FUNCTION public.record_planner_completion(
  p_session_id text, p_intent_id text, p_origin text, p_focus text,
  p_days integer, p_travelers integer, p_budget numeric, p_currency text,
  p_interests jsonb, p_comfort text, p_target_date date, p_flexibility text,
  p_intent_type text, p_destination_id text, p_occurred_at timestamptz,
  p_output_summary text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.planner_sessions (
    id, origin, focus, days, travelers, budget_amount, budget_currency,
    interests_json, comfort, target_date, date_flexibility,
    created_at, completed_at, output_summary
  ) VALUES (
    p_session_id, p_origin, p_focus, p_days, p_travelers, p_budget, p_currency,
    p_interests, p_comfort, p_target_date, p_flexibility,
    p_occurred_at, p_occurred_at, p_output_summary
  );
  INSERT INTO public.travel_intents(id, intent_type, destination_id, stage, created_at)
  VALUES (p_intent_id, p_intent_type, p_destination_id, 'planner_completed', p_occurred_at);
  INSERT INTO public.events(event_type, source, page, intent, position, occurred_at)
  VALUES ('planner_completed', 'planner_form', '/planner', p_intent_type, 'itinerary_output', p_occurred_at);
END;
$$;

-- Select and track only a verified affiliate target in one transaction.
CREATE OR REPLACE FUNCTION public.record_affiliate_click(p_product_id text, p_clicked_at timestamptz)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_url text;
  v_click_id bigint;
BEGIN
  SELECT affiliate_url INTO v_url
  FROM public.products
  WHERE product_id = p_product_id
    AND availability_state = 'confirmed'
    AND date_availability_confirmed = true
    AND affiliate_state = 'approved'
    AND affiliate_url IS NOT NULL
  FOR SHARE;

  IF v_url IS NULL OR v_url !~ '^https://[^[:space:]]+$' THEN
    RAISE EXCEPTION 'no_verified_affiliate' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO public.affiliate_clicks(product_id, destination_url, clicked_at)
  VALUES (p_product_id, v_url, p_clicked_at)
  RETURNING id INTO v_click_id;

  INSERT INTO public.events(event_type, source, page, intent, product_id, position, occurred_at)
  VALUES ('affiliate_click', 'product_card', '/mara', 'mara_3d_decision', p_product_id, v_click_id::text, p_clicked_at);

  RETURN v_url;
END;
$$;

-- A bounded aggregate payload for the authenticated Control Center.
CREATE OR REPLACE FUNCTION public.kate_control_summary()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'events', COALESCE((
      SELECT jsonb_object_agg(t.event_type, t.n)
      FROM (SELECT event_type, count(*) AS n FROM public.events GROUP BY event_type) AS t
    ), '{}'::jsonb),
    'page_views', COALESCE((
      SELECT jsonb_object_agg(t.page, t.n) FROM (
        SELECT page, count(*) AS n FROM public.events WHERE event_type = 'page_view' GROUP BY page
      ) AS t
    ), '{}'::jsonb),
    'discovery_snapshot_by_filter', COALESCE((
      SELECT jsonb_object_agg(t.search_partition, t.n)
      FROM (SELECT search_partition, count(*) AS n FROM public.products GROUP BY search_partition) AS t
    ), '{}'::jsonb),
    'conversions', (SELECT count(*) FROM public.conversions),
    'revenue', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('currency', t.currency, 'amount', t.total, 'records', t.n) ORDER BY t.currency)
      FROM (SELECT currency, round(sum(amount), 2) AS total, count(*) AS n FROM public.revenue GROUP BY currency) AS t
    ), '[]'::jsonb),
    'note', 'Snapshot partitions remain separate. No bookings, conversions or revenue are inferred.'
  );
$$;

-- No browser role may read or mutate KATE records; service_role is server-side only.
ALTER TABLE public.destinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planner_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE
  public.destinations, public.travel_intents, public.products, public.opportunities,
  public.pages, public.planner_sessions, public.events, public.affiliate_clicks,
  public.conversions, public.revenue, public.experiments, public.agent_runs,
  public.business_memory, public.incidents
FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE
  public.destinations, public.travel_intents, public.products, public.opportunities,
  public.pages, public.planner_sessions, public.events, public.affiliate_clicks,
  public.conversions, public.revenue, public.experiments, public.agent_runs,
  public.business_memory, public.incidents
TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

REVOKE ALL ON FUNCTION public.record_planner_completion(text, text, text, text, integer, integer, numeric, text, jsonb, text, date, text, text, text, timestamptz, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_planner_completion(text, text, text, text, integer, integer, numeric, text, jsonb, text, date, text, text, text, timestamptz, text) TO service_role;
REVOKE ALL ON FUNCTION public.record_affiliate_click(text, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_affiliate_click(text, timestamptz) TO service_role;
REVOKE ALL ON FUNCTION public.kate_control_summary() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.kate_control_summary() TO service_role;

-- Deterministic reference/configuration rows from the existing SQLite initializer only.
INSERT INTO public.destinations(id, name, country) VALUES
  ('nairobi', 'Nairobi', 'Kenya'),
  ('maasai-mara', 'Maasai Mara', 'Kenya')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.pages(path, page_name, intent) VALUES
  ('/', 'Home', 'kenya_trip_planning'),
  ('/planner', 'Kenya Trip Planner', 'trip_planning'),
  ('/mara', 'Nairobi–Maasai Mara · 3 days', 'mara_3d_decision'),
  ('/control', 'Control Center', 'internal_operations')
ON CONFLICT (path) DO NOTHING;

INSERT INTO public.opportunities(id, title, stage, evidence_note) VALUES
  ('KEN-20261005-01', '3-day Nairobi–Maasai Mara decision intent', 'discovery_only',
   'Intent and source limitations were supplied in the task; no conversion or revenue evidence.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.business_memory(key, value) VALUES
  ('product_data_policy', 'Discovery-only snapshots; do not claim bookability, date availability, eligibility, promotion approval, or confirmed price basis.'),
  ('affiliate_policy', 'No approved affiliate URL or commission terms are present; do not emit affiliate_click without a verified approved URL.'),
  ('preview_status', 'Planning preview only; not a booking service. No live supplier inventory is verified.'),
  ('live_inventory_gap', 'Live supplier inventory is not connected; no external integration or supplier credential entry is active.')
ON CONFLICT (key) DO NOTHING;
